version: '3'

services:
  rk.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  rk.identityserver4:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

