version: '3'

services:
  rk.web:
    image: rk.web
    build:
      context: ./RK.Web
      dockerfile: Dockerfile

  rk.identityserver4:
    image: rk.identityserver4
    build:
      context: ./../RK.IdentityServer4
      dockerfile: Dockerfile
